use std::fmt::Write as _;
use std::path::Path;
use crate::css::decl_methods;
use crate::loader::compile_tree;
use crate::types::{Compiled, IrChild, IrElem, Result, TplPart};
use crate::utils::escape;

pub fn compile_dir(root_dir: &Path) -> Result<Compiled> {
    let (doc, mut warnings) = compile_tree(root_dir)?;
    let mut out = String::new();
    writeln!(out, "// @generated by html2gpui -- DO NOT EDIT").unwrap();
    writeln!(out, "#[allow(unused_imports)]").unwrap();
    writeln!(out, "pub mod ui {{").unwrap();
    writeln!(
        out,
        "    use gpui::{{div, px, relative, rgb, FontWeight, IntoElement, ParentElement, SharedString, Styled}};"
    )
    .unwrap();
    for (name, elem) in &doc.comps {
        let mut body = String::new();
        ser_elem(elem, 8, &mut warnings, &mut body);
        writeln!(out).unwrap();
        writeln!(out, "    #[allow(dead_code)]").unwrap();
        writeln!(out, "    pub fn {name}() -> impl IntoElement {{").unwrap();
        write!(out, "{body}").unwrap();
        writeln!(out, "    }}").unwrap();
    }
    writeln!(out, "}}").unwrap();
    Ok(Compiled {
        code: out,
        warnings,
    })
}

pub fn ser_elem(e: &IrElem, ind: usize, warnings: &mut Vec<String>, out: &mut String) {
    let pad = " ".repeat(ind);
    writeln!(out, "{pad}div()").unwrap();
    for (p, v) in &e.decls {
        for m in decl_methods(p, v, warnings, &e.tag) {
            writeln!(out, "{pad}.{m}").unwrap();
        }
    }
    for c in &e.children {
        ser_child(c, ind, warnings, out);
    }
}

pub fn ser_child(c: &IrChild, ind: usize, warnings: &mut Vec<String>, out: &mut String) {
    let pad = " ".repeat(ind);
    match c {
        IrChild::Text(t) => {
            writeln!(out, r#"{pad}.child(SharedString::from("{t}"))"#).unwrap();
        }
        IrChild::Comp(f, _props) => {
            writeln!(out, "{pad}.child({f}())").unwrap();
        }
        IrChild::Div(e) => {
            writeln!(out, "{pad}.child(").unwrap();
            ser_elem(e, ind + 2, warnings, out);
            writeln!(out, "{pad})").unwrap();
        }
        IrChild::Tpl(parts) => {
            let mut out_s = String::new();
            let mut has_expr = false;
            for p in parts {
                match p {
                    TplPart::Lit(s) => out_s.push_str(s),
                    TplPart::Var(name) => out_s.push_str(&format!("{{var {name}}}")),
                    TplPart::Expr(_) => has_expr = true,
                }
            }
            if has_expr {
                warnings.push(
                    "expression binding needs the runtime renderer (debug/dev mode); emitting static text"
                        .into(),
                );
            }
            writeln!(
                out,
                r#"{pad}.child(SharedString::from("{}"))"#,
                escape(&out_s)
            )
            .unwrap();
        }
    }
}
