pub mod ast;
pub mod codegen;
pub mod css;
pub mod eval;
pub mod html;
pub mod loader;
pub mod parser;
pub mod script;
pub mod template;
pub mod tokenizer;
pub mod types;
pub mod utils;

pub use ast::{Env, Expr, Flow, FuncDef, IrScript, Stmt, Value};
pub use codegen::{compile_dir, ser_child, ser_elem};
pub use css::{box_expand, color_expr, decl_methods, len_expr, num, parse_css, parse_decls, parse_px_str, tag_defaults};
pub use eval::{binop, call, display, eval, exec, kind, truthy};
pub use html::{collect_children, compile_component_ir, collect_script_text, collect_style_text, gen_element, rewrite_component_tags, strip_script_imports};
pub use loader::{collect_files_recursive, compile_sources, compile_tree};
pub use parser::Parser;
pub use script::{env_init, env_merge, eval_expr_str, invoke, is_truthy_expr, parse_script};
pub use template::split_template;
pub use tokenizer::{tokenize, Tok};
pub use types::{Child, Compiled, Ctx, IrChild, IrDoc, IrElem, Result, TplPart};
pub use utils::{escape, pascal_case, snake_case, trim_braces};